# =============================================================
# MOSIP — ID Generator Service — Automated Setup Script
# =============================================================
# Run this script once from the directory where you cloned this repo.
#
# What it does:
#   1. Clones the MOSIP commons repository
#   2. Generates application-local.properties with all config
#   3. Builds the kernel-idgenerator-service with Maven
#   4. Starts the service
#
# Usage:
#   .\setup.ps1
#
# Optional flags:
#   -SkipClone    Skip cloning (use if you already cloned commons)
#   -SkipBuild    Skip Maven build (use if already built)
#   -NoBoot       Don't start the service after build
# =============================================================

param(
    [switch]$SkipClone,
    [switch]$SkipBuild,
    [switch]$NoBoot
)

$ErrorActionPreference = "Stop"
$Root    = $PSScriptRoot
$Version = "1.3.0"
$Port    = "8080"
$ServiceDir = "$Root\commons\kernel\kernel-idgenerator-service"
$JarPath    = "$ServiceDir\target\kernel-idgenerator-service-$Version.jar"

# ---------------------------------------------------------------
# Helper
# ---------------------------------------------------------------
function Write-Step($n, $msg) {
    Write-Host ""
    Write-Host "[$n] $msg" -ForegroundColor Cyan
    Write-Host ("-" * 55) -ForegroundColor DarkGray
}

function Assert-Tool($cmd, $hint) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        Write-Host "ERROR: '$cmd' not found. $hint" -ForegroundColor Red
        exit 1
    }
}

# ---------------------------------------------------------------
# 0. Check prerequisites
# ---------------------------------------------------------------
Write-Host ""
Write-Host "=======================================================" -ForegroundColor Magenta
Write-Host "   MOSIP ID Generator — Automated Setup" -ForegroundColor Magenta
Write-Host "=======================================================" -ForegroundColor Magenta

Write-Step "0" "Checking prerequisites..."
Assert-Tool "java"  "Install JDK 21 from https://adoptium.net"
Assert-Tool "mvn"   "Install Maven 3.6+ from https://maven.apache.org/download.cgi"
Assert-Tool "git"   "Install Git from https://git-scm.com"

$javaVer = java -version 2>&1 | Select-String "version" | Out-String
$mvnVer  = mvn -version 2>&1 | Select-String "Apache Maven" | Out-String
Write-Host "  Java : $($javaVer.Trim())" -ForegroundColor Green
Write-Host "  Maven: $($mvnVer.Trim())" -ForegroundColor Green

# ---------------------------------------------------------------
# 1. Clone MOSIP commons
# ---------------------------------------------------------------
Write-Step "1" "Cloning MOSIP commons repository..."

if ($SkipClone) {
    Write-Host "  --SkipClone set. Using existing commons folder." -ForegroundColor Yellow
} elseif (Test-Path "$Root\commons") {
    Write-Host "  commons/ already exists. Skipping clone." -ForegroundColor Yellow
    Write-Host "  (Delete the commons/ folder and re-run to get a fresh clone)" -ForegroundColor DarkGray
} else {
    Write-Host "  Cloning from https://github.com/mosip/commons.git ..." -ForegroundColor Gray
    git clone --depth 1 --branch master https://github.com/mosip/commons.git "$Root\commons"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  ERROR: Clone failed. Check your internet connection." -ForegroundColor Red
        exit 1
    }
    Write-Host "  Cloned successfully." -ForegroundColor Green
}

# ---------------------------------------------------------------
# 2. Generate application-local.properties
# ---------------------------------------------------------------
Write-Step "2" "Writing application-local.properties..."

$propsPath = "$ServiceDir\src\main\resources\application-local.properties"

$config = @"
# ============================================================
# Auto-generated by setup.ps1 — do NOT commit this file
# ============================================================

# ---- Database (H2 in-memory — no install needed) -----------
javax.persistence.jdbc.driver=org.h2.Driver
id_database_url=jdbc:h2:mem:mosip_kernel;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
id_database_username=kerneluser
id_database_password=Mosip@dev123
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.jdbc.lob.non_contextual_creation=true
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.connection.charSet=utf8
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false
hibernate.cache.use_structured_entries=false
hibernate.generate_statistics=false
spring.datasource.initialization-mode=always
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.h2.console.enabled=true

# ---- Auth (bypassed in local mode) -------------------------
auth.server.validate.url=https://dev.mosip.io/v1/authmanager/authorize/validateToken
mosip.auth.adapter.impl.basepackage=io.mosip.kernel.idgenerator.localauth
auth.server.admin.offline.token.validate=false
auth.jwt.secret=authjwtsecret
auth.jwt.base=Mosip-Token
mosip.kernel.auth.appids.realm.map={regproc:'mosip'}

# ---- VID Properties ----------------------------------------
mosip.kernel.vid.length=16
mosip.kernel.vid.length.sequence-limit=3
mosip.kernel.vid.length.repeating-block-limit=2
mosip.kernel.vid.length.repeating-limit=2
mosip.kernel.vid.not-start-with=0,1
mosip.kernel.vid.restricted-numbers=786,666
mosip.kernel.vid.min-unused-threshold=5
mosip.kernel.vid.vids-to-generate=10
mosip.kernel.vid.time-to-release-after-expiry=5
mosip.kernel.vid.pool-population-timeout=1000000

# VID revoke scheduler (daily at 17:19)
kernel.vid.revoke-scheduler-type=cron
kernel.vid.revoke-scheduler-seconds=0
kernel.vid.revoke-scheduler-minutes=19
kernel.vid.revoke-scheduler-hours=17
kernel.vid.revoke-scheduler-days_of_month=*
kernel.vid.revoke-scheduler-months=*
kernel.vid.revoke-scheduler-days_of_week=*

# VID isolator scheduler (every hour)
kernel.vid.isolator-scheduler-type=cron
kernel.vid.isolator-scheduler-seconds=0
kernel.vid.isolator-scheduler-minutes=0
kernel.vid.isolator-scheduler-hours=*
kernel.vid.isolator-scheduler-days_of_month=*
kernel.vid.isolator-scheduler-months=*
kernel.vid.isolator-scheduler-days_of_week=*

# ---- UIN Properties ----------------------------------------
mosip.kernel.uin.length=10
mosip.kernel.uin.min-unused-threshold=100000
mosip.kernel.uin.uins-to-generate=2000
mosip.kernel.uin.restricted-numbers=786,666
mosip.kernel.uin.not-start-with=0,1
mosip.kernel.uin.length.sequence-limit=3
mosip.kernel.uin.length.repeating-block-limit=2
mosip.kernel.uin.length.repeating-limit=2
mosip.kernel.uin.length.reverse-digits-limit=5
mosip.kernel.uin.length.digits-limit=5
mosip.kernel.uin.length.conjugative-even-digits-limit=3
mosip.kernel.uin.status.unused=UNUSED
mosip.kernel.uin.status.issued=ISSUED
mosip.kernel.uin.status.assigned=ASSIGNED
mosip.kernel.uin.status.unassigned=UNASSIGNED
mosip.kernel.uin.get_executor_pool=400
mosip.kernel.uin.hikari_maximumPoolSize=400

# UIN transfer scheduler (daily at 17:48)
kernel.uin.transfer-scheduler-type=cron
kernel.uin.transfer-scheduler-seconds=0
kernel.uin.transfer-scheduler-minutes=48
kernel.uin.transfer-scheduler-hours=17
kernel.uin.transfer-scheduler-days_of_month=*
kernel.uin.transfer-scheduler-months=*
kernel.uin.transfer-scheduler-days_of_week=*

# ---- Crypto ------------------------------------------------
mosip.kernel.crypto.asymmetric-algorithm-name=RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING
mosip.kernel.crypto.symmetric-algorithm-name=AES/GCM/PKCS5Padding
mosip.kernel.keygenerator.asymmetric-algorithm-name=RSA
mosip.kernel.keygenerator.symmetric-algorithm-name=AES
mosip.kernel.keygenerator.asymmetric-key-length=2048
mosip.kernel.keygenerator.symmetric-key-length=256
mosip.kernel.data-key-splitter=#KEY_SPLITTER#
mosip.kernel.crypto.gcm-tag-length=128
mosip.kernel.crypto.hash-algorithm-name=PBKDF2WithHmacSHA512
mosip.kernel.crypto.hash-symmetric-key-length=256
mosip.kernel.crypto.hash-iteration=100000
mosip.kernel.crypto.sign-algorithm-name=RS256

# ---- Signature ---------------------------------------------
mosip.kernel.signature.signature-request-id=SIGNATURE.REQUEST
mosip.kernel.signature.signature-version-id=v1.0
mosip.kernel.keymanager-service-sign-url=https://dev.mosip.io/v1/keymanager/sign
mosip.kernel.keymanager-service-publickey-url=https://dev.mosip.io/v1/keymanager/publickey/{applicationId}
"@

# Create the resources dir if it doesn't exist yet
$propsDir = Split-Path $propsPath
if (-not (Test-Path $propsDir)) {
    New-Item -ItemType Directory -Path $propsDir | Out-Null
}

Set-Content -Path $propsPath -Value $config -Encoding UTF8
Write-Host "  Written: $propsPath" -ForegroundColor Green

# ---------------------------------------------------------------
# 3. Build with Maven
# ---------------------------------------------------------------
Write-Step "3" "Building with Maven (this may take a few minutes)..."

if ($SkipBuild) {
    Write-Host "  --SkipBuild set. Skipping Maven build." -ForegroundColor Yellow
    if (-not (Test-Path $JarPath)) {
        Write-Host "  ERROR: JAR not found at $JarPath" -ForegroundColor Red
        Write-Host "  Run without -SkipBuild to build first." -ForegroundColor Red
        exit 1
    }
} else {
    Push-Location "$Root\commons"
    try {
        mvn clean install -pl kernel/kernel-idgenerator-service -am -DskipTests
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  ERROR: Maven build failed." -ForegroundColor Red
            exit 1
        }
    } finally {
        Pop-Location
    }
    Write-Host "  Build successful." -ForegroundColor Green
}

# ---------------------------------------------------------------
# 4. Start the service
# ---------------------------------------------------------------
Write-Step "4" "Starting the ID Generator Service..."

if ($NoBoot) {
    Write-Host "  --NoBoot set. Not starting the service." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  To start manually, run:" -ForegroundColor White
    Write-Host "  java -jar `"$JarPath`"" -ForegroundColor Cyan
    exit 0
}

Write-Host ""
Write-Host "  Service starting on http://localhost:$Port/v1/idgenerator" -ForegroundColor Magenta
Write-Host ""
Write-Host "  Useful URLs:" -ForegroundColor White
Write-Host "    Health  : http://localhost:$Port/v1/idgenerator/actuator/health" -ForegroundColor Cyan
Write-Host "    H2 DB   : http://localhost:$Port/h2-console" -ForegroundColor Cyan
Write-Host "             (JDBC: jdbc:h2:mem:mosip_kernel  user: kerneluser  pass: Mosip@dev123)" -ForegroundColor DarkCyan
Write-Host "    Metrics : http://localhost:$Port/v1/idgenerator/actuator/prometheus" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Press Ctrl+C to stop." -ForegroundColor DarkYellow
Write-Host ""

java -jar "$JarPath"
